version: '3.7'

services:
  haalcentraal.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=changeit
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/haalcentraal.pfx
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./certificate/oidc:/https:ro
      - ./certificate/oidc:/usr/local/share/ca-certificates
      - ./certificate/ca:/root/.local/share/mkcert/

  haalcentraal.viewer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5011;http://+:5010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=changeit
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/haalcentraal.pfx
    ports:
      - "5010:5010"
      - "5011:5011"
    volumes:
      - ./certificate/viewer:/https:ro
      - ./certificate/viewer:/usr/local/share/ca-certificates
      - ./certificate/ca:/root/.local/share/mkcert/
      - ./config/HaalCentraal.Viewer:/app/config

  haalcentraal.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5021;http://+:5020
      - ASPNETCORE_Kestrel__Certificates__Default__Password=changeit
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/haalcentraal.pfx
    ports:
      - "5020:5020"
      - "5021:5021"
    volumes:
      - ./certificate:/https:ro
      - ./certificate:/usr/local/share/ca-certificates
      - ./certificate:/root/.local/share/mkcert/

  haalcentraal.brkbevragen:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
